from enum import Enum

class TaskType(str, Enum):
    MESSAGE = "MESSAGE"
    FOLLOW_UP_1 = "FOLLOW_UP_1"
    FOLLOW_UP_2 = "FOLLOW_UP_2"

class TaskStatus(str, Enum):
    CREATED = "CREATED"
    VALIDATING = "VALIDATING"
    QUEUED = "QUEUED"
    READY = "READY"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    RETRY_WAIT = "RETRY_WAIT"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    SKIPPED = "SKIPPED"
    CANCELLED = "CANCELLED"
    INTERRUPTED = "INTERRUPTED"
    RECONCILING = "RECONCILING"

class MessageStatus(str, Enum):
    PENDING = "PENDING"
    VERIFYING = "VERIFYING"
    VERIFIED = "VERIFIED"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    APPROVED = "APPROVED"
    SENDING = "SENDING"
    SENT = "SENT"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    UNKNOWN = "UNKNOWN"

class VerificationDecision(str, Enum):
    HIGH_CONFIDENCE = "HIGH_CONFIDENCE"
    MEDIUM_CONFIDENCE = "MEDIUM_CONFIDENCE"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    MISMATCH = "MISMATCH"

class ResultCode(str, Enum):
    SUCCESS = "SUCCESS"
    DM_NOT_AVAILABLE = "DM_NOT_AVAILABLE"
    LOGIN_REQUIRED = "LOGIN_REQUIRED"
    CHALLENGE_REQUIRED = "CHALLENGE_REQUIRED"
    PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND"
    PROFILE_MISMATCH = "PROFILE_MISMATCH"
    SEND_FAILED = "SEND_FAILED"
    NETWORK_ERROR = "NETWORK_ERROR"
    TIMEOUT = "TIMEOUT"
    RATE_LIMITED = "RATE_LIMITED"
    UNKNOWN = "UNKNOWN"

class WorkerStatus(str, Enum):
    IDLE = "IDLE"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    STOPPED = "STOPPED"
    ERROR = "ERROR"

class AutomationStage(str, Enum):
    IDLE = "IDLE"
    INITIALIZING = "INITIALIZING"
    CHECKING_LOGIN = "CHECKING_LOGIN"
    CLAIMING_TASK = "CLAIMING_TASK"
    OPENING_PROFILE = "OPENING_PROFILE"
    WAITING_FOR_PROFILE = "WAITING_FOR_PROFILE"
    EXTRACTING_PROFILE = "EXTRACTING_PROFILE"
    VERIFYING = "VERIFYING"
    CHECKING_DM_AVAILABILITY = "CHECKING_DM_AVAILABILITY"
    OPENING_COMPOSER = "OPENING_COMPOSER"
    PREPARING_MESSAGE = "PREPARING_MESSAGE"
    SENDING_MESSAGE = "SENDING_MESSAGE"
    DETECTING_RESULT = "DETECTING_RESULT"
    RECONCILING = "RECONCILING"
    COMPLETED = "COMPLETED"
    ERROR = "ERROR"

class RepliedStatus(str, Enum):
    UNKNOWN = "UNKNOWN"
    YES = "YES"
    NO = "NO"

class SourceType(str, Enum):
    XLSX = "XLSX"
    BROWSER_SHEET = "BROWSER_SHEET"

class SourceStatus(str, Enum):
    PENDING = "PENDING"
    ACCESSIBLE = "ACCESSIBLE"
    ACCESS_PROHIBITED = "ACCESS_PROHIBITED"
    SYNCED = "SYNCED"
    ERROR = "ERROR"

class EventCode(str, Enum):
    SOURCE_IMPORTED = "SOURCE_IMPORTED"
    SOURCE_ACCESS_CHECKED = "SOURCE_ACCESS_CHECKED"
    CONTACT_CREATED = "CONTACT_CREATED"
    CONTACT_UPDATED = "CONTACT_UPDATED"
    TASK_CREATED = "TASK_CREATED"
    TASK_STARTED = "TASK_STARTED"
    VERIFICATION_STARTED = "VERIFICATION_STARTED"
    VERIFICATION_COMPLETED = "VERIFICATION_COMPLETED"
    MESSAGE_ATTEMPTED = "MESSAGE_ATTEMPTED"
    MESSAGE_CONFIRMED = "MESSAGE_CONFIRMED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"
    TASK_RETRY_SCHEDULED = "TASK_RETRY_SCHEDULED"
    WORKER_STARTED = "WORKER_STARTED"
    WORKER_STOPPED = "WORKER_STOPPED"
    WORKER_PAUSED = "WORKER_PAUSED"
    WORKER_RESUMED = "WORKER_RESUMED"
    LOGIN_REQUIRED = "LOGIN_REQUIRED"
    LOGIN_DETECTED = "LOGIN_DETECTED"
    ACCESS_PROHIBITED = "ACCESS_PROHIBITED"
    NETWORK_OFFLINE = "NETWORK_OFFLINE"
    NETWORK_ONLINE = "NETWORK_ONLINE"
    RECOVERY_STARTED = "RECOVERY_STARTED"
    RECOVERY_COMPLETED = "RECOVERY_COMPLETED"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    STAGE_CHANGED = "STAGE_CHANGED"

class Severity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"

class NetworkStatus(str, Enum):
    ONLINE = "ONLINE"
    DEGRADED = "DEGRADED"
    OFFLINE = "OFFLINE"
